-- Time Intelligence: Schema DDL

CREATE DATABASE IF NOT EXISTS SNIPPETS;
CREATE SCHEMA IF NOT EXISTS SNIPPETS.PUBLIC;

USE DATABASE SNIPPETS;
USE SCHEMA PUBLIC;

CREATE OR REPLACE TABLE DIM_CALENDAR (
    MONTH       DATE         PRIMARY KEY COMMENT 'First day of the month (e.g. 2024-03-01)',
    MONTH_NAME  VARCHAR(10)  COMMENT 'January, February, ...',
    QUARTER     NUMBER(1)    COMMENT '1–4',
    YEAR        NUMBER(4)    COMMENT '2023, 2024, ...'
);

CREATE OR REPLACE TABLE FACT_SALES (
    ROW_ID      NUMBER AUTOINCREMENT PRIMARY KEY,
    SALE_MONTH  DATE         COMMENT 'First day of the sale month — FK to DIM_CALENDAR.MONTH',
    REGION      VARCHAR(50),
    REVENUE     FLOAT,
    UNITS       NUMBER
);
