from datetime import timedelta

from tecton import *
from tecton.framework.configs import DatetimePartitionColumn
from tecton.types import *

datetime_partition_columns = [
    DatetimePartitionColumn(column_name="dt", datepart="date", format_string="%Y-%m-%d"),
]

example_traffic_stream = StreamSource(
    name="example_traffic_stream",
    stream_config=PushConfig(timestamp_field="EventTimestamp"),
    batch_config=FileConfig(
        uri="s3://example-feature-store/sources/traffic/",
        file_format="parquet",
        timestamp_field="EventTimestamp",
        timestamp_format="%Y-%m-%dT%H:%M:%SZ",
        datetime_partition_columns=datetime_partition_columns,
        data_delay=timedelta(hours=4),
    ),
    schema=[
        Field("DriverUuid", String),
        Field("TripType", String),
        Field("TripDirection", String),
        Field("TripStatusDs", String),
        Field("TripTraceUuid", String),
        Field("EventTimestamp", Timestamp),
        Field("CurrencyCode", String),
        Field("FareAmount", Float64),
        Field("AccountBalance", Float64),
        Field("LaneId", String),
        Field("OriginVehicleId", String),
        Field("OriginDriverUuid", String),
        Field("OriginNameDs", String),
        Field("OriginAgencyCode", String),
        Field("OriginCheckpointCode", String),
        Field("OriginPermitNumber", String),
        Field("OriginCountryCode", String),
        Field("OriginPermitCreatedDt", Timestamp),
        Field("SensorId", String),
        Field("CheckpointAddressDs", String),
        Field("OriginGeoLatDs", String),
        Field("OriginGeoLonDs", String),
        Field("DestVehicleId", String),
        Field("DestDriverUuid", String),
        Field("DestNameDs", String),
        Field("DestAgencyCode", String),
        Field("DestCheckpointCode", String),
        Field("DestPermitNumber", String),
        Field("DestCountryCode", String),
        Field("DestPermitCreatedDt", Timestamp),
        Field("DestRegistryLastUpdateDt", Timestamp),
        Field("DestViolationLastUpdateDt", Timestamp),
        Field("DestIncidentLastUpdateDt", Timestamp),
        Field("DestSettleLastUpdateDt", Timestamp),
        Field("DestSettleCount90d", Int64),
        Field("DestSettleCount12m", Int64),
        Field("DestSettleCount60m", Int64),
        Field("DestIncidentFlag90d", Int64),
        Field("DestIncidentFlag12m", Int64),
        Field("DestIncidentFlag60m", Int64),
        Field("DestViolationTypeA90d", Int64),
        Field("DestViolationTypeA12m", Int64),
        Field("DestViolationTypeA60m", Int64),
        Field("DestViolationTypeB90d", Int64),
        Field("DestViolationTypeB12m", Int64),
        Field("DestViolationTypeB60m", Int64),
        Field("DestViolationTypeC90d", Int64),
        Field("DestViolationTypeC12m", Int64),
        Field("DestViolationTypeC60m", Int64),
        Field("DestViolationUnknown90d", Int64),
        Field("DestViolationUnknown12m", Int64),
        Field("DestViolationUnknown60m", Int64),
        Field("DestIncidentTotalAmt90d", Int64),
        Field("DestIncidentTotalAmt12m", Int64),
        Field("DestIncidentTotalAmt60m", Int64),
        Field("DestIncidentReporters90d", Int64),
        Field("DestIncidentReporters12m", Int64),
        Field("DestIncidentReporters60m", Int64),
        Field("DestIncidentOpenReports", Int64),
        Field("DestIncidentOpenReportsDist", Int64),
        Field("DestIncidentRejReports90d", Int64),
        Field("DestIncidentRejReports12m", Int64),
        Field("DestIncidentRejReports60m", Int64),
        Field("DestRegistryPermits", Int64),
        Field("RoadZoneRegion", String),
        Field("RoadZoneCity", String),
        Field("RoadZoneCountryCode", String),
        Field("TollId", String),
        Field("TollMode", Int64),
        Field("PermitBarcode", String),
        Field("OriginFareAmount", Float64),
        Field("TollStatus", String),
        Field("OriginPermitName", String),
        Field("OriginPermitKey", String),
        Field("OriginAcctAgencyCode", String),
        Field("OriginAcctCheckpointCode", String),
        Field("OriginAcctPermitNumber", String),
        Field("OriginAcctCountryCode", String),
        Field("OriginAcctCreatedDt", Timestamp),
        Field("TollSubtype", String),
        # Driver / Vehicle Data
        Field("DriverName", String),
        Field("DriverBirthdate", Timestamp),
        Field("DriverOccupation", String),
        Field("VehicleLicenseId", String),
        Field("VehicleRegisteredDt", Timestamp),
        Field("VehicleClass", String),
        Field("DriverStreet", String),
        Field("DriverStreetNumber", String),
        Field("DriverStreetUnit", String),
        Field("DriverNeighborhood", String),
        Field("DriverCity", String),
        Field("DriverState", String),
        Field("DriverPostalCode", String),
        Field("DriverEmail", String),
        Field("DriverPhoneAreaCode", String),
        Field("DriverPhoneNumber", String),
    ],
)
