"""Validation for Phase 1: Observe."""

from __future__ import annotations

from typing import Any

from .common import artifact_state_path, has_observed_state, has_user_agreement, phase_artifact, validate_artifact_location, validate_phase_log_entry


_REQUIRED_OBSERVE_SECTIONS = {
    "session": ("account", "region", "role", "role_sufficient"),
    "managed_state": ("status", "location_checked"),
    "scope_observed": ("requested_scope", "objects_observed", "observation_coverage"),
    "observation_boundary": ("excluded_system_databases", "data_freshness"),
    "account_overview": ("visible_non_system_databases", "counts"),
    "live_governance": ("policies", "tags", "classifications", "protected_data"),
    "governance_object_catalog": ("policies", "tags", "classification_profiles", "custom_classifiers"),
}

_REQUIRED_ACCOUNT_COUNTS = (
    "databases",
    "schemas",
    "tables_or_views",
    "roles",
    "data_policies",
    "tags",
    "tag_bindings",
    "classification_profiles",
    "custom_classifiers",
)

_VALID_MANAGED_STATE_STATUSES = {"found", "missing", "unreadable", "handoff_required", "not_writable"}
_VALID_OBSERVATION_COVERAGE = {"complete", "partial_due_to_privilege", "partial_due_to_scope", "intent_only"}
_REQUIRED_OBSERVATION_HEADINGS = (
    "Purpose",
    "Artifact and State Locations",
    "Observation Boundary",
    "Capability / Privilege Check",
    "Account Overview",
    "Governance Scope Inventory",
    "Observed Gaps / Review Areas",
    "Unprotected / Unclassified Scopes",
    "Governance Object Catalog",
    "Limitations and Confidence",
)


_SCOPE_REQUIRED_FIELDS = (
    "scope_id",
    "name",
    "status",
    "objects_in_scope",
    "controls_used",
    "key_gaps",
)


def validate_artifact(state: dict[str, Any]) -> list[str]:
    errors = validate_phase_log_entry(state, 1, "observe")
    artifact = phase_artifact(state, "observe")
    if artifact is None:
        errors.append("missing phase_details.observe")
    else:
        errors.extend(validate_artifact_location(artifact, "observe", 1))
        errors.extend(_validate_observe_artifact(artifact))
    if not has_observed_state(state):
        errors.append("observed_fetched_at is required")
    if not isinstance(state.get("artifacts"), dict):
        errors.append("artifacts must be present")
    return errors


def can_exit_phase(state: dict[str, Any]) -> bool:
    return not validate_artifact(state) and has_user_agreement(state, 1)


def render_observation_summary(state: dict[str, Any]) -> str:
    artifact = phase_artifact(state, "observe") or {}
    scope = artifact.get("scope_observed", {}) if isinstance(artifact.get("scope_observed"), dict) else {}
    boundary = artifact.get("observation_boundary", {}) if isinstance(artifact.get("observation_boundary"), dict) else {}
    overview = artifact.get("account_overview", {}) if isinstance(artifact.get("account_overview"), dict) else {}
    live_governance = artifact.get("live_governance", {}) if isinstance(artifact.get("live_governance"), dict) else {}
    catalog = artifact.get("governance_object_catalog", {}) if isinstance(artifact.get("governance_object_catalog"), dict) else {}
    session = artifact.get("session", {}) if isinstance(artifact.get("session"), dict) else {}
    managed_state = artifact.get("managed_state", {}) if isinstance(artifact.get("managed_state"), dict) else {}
    location = artifact.get("artifact_location", {}) if isinstance(artifact.get("artifact_location"), dict) else {}
    progress = artifact.get("progress", {}) if isinstance(artifact.get("progress"), dict) else {}

    lines = [
        "# Observation Summary — Account Governance Baseline",
        "",
        "## Purpose",
        "This report establishes a complete, auditable baseline of visible non-system Snowflake governance controls before any changes are discussed.",
        "",
        "## Artifact and State Locations",
        "",
        f"- Report generated at: `{_text(location.get('last_updated_at'), _text(artifact.get('observed_fetched_at'), 'unknown'))}`",
        f"- Working state: `{_text(artifact_state_path(location), 'unknown')}`",
        f"- Customer artifact: `{_text(location.get('customer_artifact_path'), 'unknown')}`",
        f"- Managed state status: `{_text(managed_state.get('status'), 'unknown')}`",
        f"- Base committed version: `{_optional_text(progress.get('base_committed_version'), 'none')}`",
        "- Generated by: Intent-driven Governance skill, Phase 1 Observe",
        "",
        "## Observation Boundary",
        "",
        f"- Account: `{_text(session.get('account'), 'unknown')}`",
        f"- Region: `{_text(session.get('region'), 'unknown')}`",
        f"- Role: `{_text(session.get('role'), 'unknown')}`",
        f"- User: `{_text(session.get('user'), 'unknown')}`",
        f"- Requested scope: `{_text(scope.get('requested_scope'), 'full visible non-system account')}`",
        f"- Observation coverage: `{_coverage(scope, artifact)}`",
        f"- Excluded system databases: {_join_code(boundary.get('excluded_system_databases'))}",
        f"- Data freshness: {_text(boundary.get('data_freshness'), 'realtime metadata where available')}",
        "",
        "## Capability / Privilege Check",
        "",
        f"- Selected mode: `{_selected_mode(artifact, managed_state, scope)}`",
        f"- Artifact workspace status: `{_text(managed_state.get('status'), 'unknown')}`",
        f"- `ACCOUNT_USAGE` status: `{_account_usage_status(artifact, boundary)}`",
        f"- Observation capability: `{_coverage(scope, artifact)}`",
        f"- Execution capability: `{_execution_capability(artifact)}`",
        f"- Capability limitations: {_join(artifact.get('limitations'))}",
        "",
        "## Account Overview",
    ]
    lines.extend(_count_lines(overview.get("counts")))
    lines.extend(_visible_database_lines(overview.get("visible_non_system_databases")))

    lines.extend(["", "## Governance Scope Inventory"])
    lines.extend(_scope_inventory_lines(artifact.get("scope_inventory")))

    lines.extend(["", "## Observed Gaps / Review Areas"])
    observed_gaps = artifact.get("observed_gaps", [])
    if isinstance(observed_gaps, list) and observed_gaps:
        lines.extend(f"- {item}" for item in observed_gaps)
    else:
        lines.append("- None observed")

    lines.extend(["", "## Unprotected / Unclassified Scopes"])
    unprotected = artifact.get("unprotected_objects", [])
    lines.extend(f"- {item}" for item in unprotected) if isinstance(unprotected, list) and unprotected else lines.append("- None observed outside scope inventory")

    lines.extend(["", "## Governance Object Catalog"])
    lines.extend(_catalog_lines(catalog, live_governance))

    lines.extend(["", "## Limitations and Confidence"])
    limitations = artifact.get("limitations", [])
    lines.extend(f"- {item}" for item in limitations) if isinstance(limitations, list) and limitations else lines.append("- None")
    return "\n".join(lines)


def _validate_observe_artifact(artifact: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    for section, required_fields in _REQUIRED_OBSERVE_SECTIONS.items():
        value = artifact.get(section)
        if not isinstance(value, dict):
            errors.append(f"phase_details.observe.{section} must be a mapping")
            continue
        for field in required_fields:
            if field not in value:
                errors.append(f"phase_details.observe.{section}.{field} is required")

    managed_state = artifact.get("managed_state")
    if isinstance(managed_state, dict):
        status = managed_state.get("status")
        if status not in _VALID_MANAGED_STATE_STATUSES:
            errors.append(
                "phase_details.observe.managed_state.status must be one of "
                f"{sorted(_VALID_MANAGED_STATE_STATUSES)}"
            )

    for list_field in ("scope_inventory", "unprotected_objects", "limitations"):
        if list_field in artifact and not isinstance(artifact[list_field], list):
            errors.append(f"phase_details.observe.{list_field} must be a list")
    if not isinstance(artifact.get("observed_gaps"), list):
        errors.append("phase_details.observe.observed_gaps must be a list")

    errors.extend(_validate_account_overview(artifact.get("account_overview")))
    errors.extend(_validate_scope_inventory(artifact.get("scope_inventory")))
    errors.extend(_validate_visible_database_coverage(artifact))
    errors.extend(_validate_governance_object_catalog(artifact.get("governance_object_catalog")))

    if not isinstance(artifact.get("observation_summary"), str) or not artifact.get("observation_summary", "").strip():
        errors.append("phase_details.observe.observation_summary must be a non-empty string")
    else:
        summary = artifact["observation_summary"]
        if "# Observation Summary — Account Governance Baseline" not in summary:
            errors.append("phase_details.observe.observation_summary missing required title: Observation Summary — Account Governance Baseline")
        for heading in _REQUIRED_OBSERVATION_HEADINGS:
            if heading not in summary:
                errors.append(f"phase_details.observe.observation_summary missing required section: {heading}")

    live_governance = artifact.get("live_governance")
    if isinstance(live_governance, dict):
        for list_field in ("policies", "tags", "classifications", "protected_data"):
            if not isinstance(live_governance.get(list_field), list):
                errors.append(f"phase_details.observe.live_governance.{list_field} must be a list")
        for idx, item in enumerate(live_governance.get("protected_data", [])):
            if not isinstance(item, dict):
                errors.append(f"phase_details.observe.live_governance.protected_data[{idx}] must be a mapping")
                continue
            if not isinstance(item.get("object"), str) or not item.get("object", "").strip():
                errors.append(f"phase_details.observe.live_governance.protected_data[{idx}].object is required")
            observed = item.get("observed")
            if not isinstance(observed, dict) or not isinstance(observed.get("how"), list):
                errors.append(f"phase_details.observe.live_governance.protected_data[{idx}].observed.how must be a list")

    scope_observed = artifact.get("scope_observed")
    if isinstance(scope_observed, dict) and scope_observed.get("observation_coverage") not in _VALID_OBSERVATION_COVERAGE:
        errors.append(
            "phase_details.observe.scope_observed.observation_coverage must be one of "
            f"{sorted(_VALID_OBSERVATION_COVERAGE)}"
        )

    if not isinstance(artifact.get("ready_for_intent_capture"), bool):
        errors.append("phase_details.observe.ready_for_intent_capture must be a boolean")
    return errors


def _validate_account_overview(value: Any) -> list[str]:
    errors: list[str] = []
    if not isinstance(value, dict):
        return errors
    counts = value.get("counts")
    if not isinstance(value.get("visible_non_system_databases"), list):
        errors.append("phase_details.observe.account_overview.visible_non_system_databases must be a list")
    if not isinstance(counts, dict):
        errors.append("phase_details.observe.account_overview.counts must be a mapping")
        return errors
    for field in _REQUIRED_ACCOUNT_COUNTS:
        if field not in counts:
            errors.append(f"phase_details.observe.account_overview.counts.{field} is required")
    return errors


def _validate_visible_database_coverage(artifact: dict[str, Any]) -> list[str]:
    overview = artifact.get("account_overview") if isinstance(artifact.get("account_overview"), dict) else {}
    boundary = artifact.get("observation_boundary") if isinstance(artifact.get("observation_boundary"), dict) else {}
    visible = overview.get("visible_non_system_databases")
    if not isinstance(visible, list):
        return []
    uninspected = boundary.get("uninspected_visible_non_system_databases", [])
    if not isinstance(uninspected, list):
        return ["phase_details.observe.observation_boundary.uninspected_visible_non_system_databases must be a list when present"]
    covered: list[str] = []
    for scope in artifact.get("scope_inventory", []):
        if isinstance(scope, dict) and isinstance(scope.get("databases"), list):
            covered.extend(str(database) for database in scope["databases"])
    accounted = set(covered) | {str(database) for database in uninspected}
    missing = sorted(str(database) for database in visible if str(database) not in accounted)
    if missing:
        return [
            "phase_details.observe.scope_inventory must account for every visible non-system database; "
            f"missing: {missing}"
        ]
    duplicates = sorted(database for database in set(covered) if covered.count(database) > 1)
    if duplicates:
        return [
            "phase_details.observe.scope_inventory[].databases must account for each visible non-system database at most once; "
            f"duplicates: {duplicates}"
        ]
    return []


def _validate_scope_inventory(value: Any) -> list[str]:
    errors: list[str] = []
    if not isinstance(value, list) or not value:
        return ["phase_details.observe.scope_inventory must contain at least one scope"]
    seen_ids: set[str] = set()
    for idx, item in enumerate(value):
        if not isinstance(item, dict):
            errors.append(f"phase_details.observe.scope_inventory[{idx}] must be a mapping")
            continue
        for field in _SCOPE_REQUIRED_FIELDS:
            if field not in item:
                errors.append(f"phase_details.observe.scope_inventory[{idx}].{field} is required")
        scope_id = item.get("scope_id")
        if isinstance(scope_id, str) and scope_id:
            if scope_id in seen_ids:
                errors.append(f"phase_details.observe.scope_inventory[{idx}].scope_id must be unique")
            seen_ids.add(scope_id)
        if "databases" in item and not isinstance(item["databases"], list):
            errors.append(f"phase_details.observe.scope_inventory[{idx}].databases must be a list")
        if not isinstance(item.get("objects_in_scope"), list):
            errors.append(f"phase_details.observe.scope_inventory[{idx}].objects_in_scope must be a list")
        if not isinstance(item.get("controls_used"), list):
            errors.append(f"phase_details.observe.scope_inventory[{idx}].controls_used must be a list")
        if not isinstance(item.get("key_gaps"), list):
            errors.append(f"phase_details.observe.scope_inventory[{idx}].key_gaps must be a list")
    return errors


def _validate_governance_object_catalog(value: Any) -> list[str]:
    errors: list[str] = []
    if not isinstance(value, dict):
        return errors
    for list_field in ("policies", "tags", "classification_profiles", "custom_classifiers"):
        if not isinstance(value.get(list_field), list):
            errors.append(f"phase_details.observe.governance_object_catalog.{list_field} must be a list")
    return errors


def _coverage(scope: dict[str, Any], artifact: dict[str, Any]) -> str:
    if artifact.get("limitations"):
        return "complete with limitations"
    coverage = scope.get("observation_coverage")
    return str(coverage) if coverage else "unknown"


def _selected_mode(artifact: dict[str, Any], managed_state: dict[str, Any], scope: dict[str, Any]) -> str:
    explicit = artifact.get("selected_mode") or artifact.get("workflow_mode")
    if isinstance(explicit, str) and explicit.strip():
        return explicit.strip()
    if scope.get("observation_coverage") == "intent_only":
        return "intent_only"
    if managed_state.get("status") in {"handoff_required", "not_writable"}:
        return "handoff_required"
    return "observe_and_capture_when_confirmed"


def _account_usage_status(artifact: dict[str, Any], boundary: dict[str, Any]) -> str:
    for value in (
        boundary.get("account_usage_status"),
        artifact.get("account_usage_status"),
        boundary.get("account_usage_availability"),
        artifact.get("account_usage_availability"),
    ):
        if isinstance(value, str) and value.strip():
            return value.strip()
    return "not recorded"


def _execution_capability(artifact: dict[str, Any]) -> str:
    value = artifact.get("execution_readiness") or artifact.get("execution_capability")
    if isinstance(value, str) and value.strip():
        return value.strip()
    if artifact.get("ready_for_intent_capture") is False:
        return "not ready for downstream execution planning"
    return "not assessed in Phase 1 durable state"


def _count_lines(value: Any) -> list[str]:
    if not isinstance(value, dict) or not value:
        return ["- Counts unavailable"]
    labels = {
        "databases": "Visible non-system databases",
        "schemas": "Schemas",
        "tables_or_views": "Tables/views",
        "columns": "Columns",
        "roles": "Roles",
        "data_policies": "Data policies",
        "masking_policies": "Masking policies",
        "row_access_policies": "Row access policies",
        "aggregation_policies": "Aggregation policies",
        "projection_policies": "Projection policies",
        "tags": "Tags",
        "tag_bindings": "Tag bindings",
        "classification_profiles": "Classification profiles",
        "custom_classifiers": "Custom classifiers",
    }
    lines: list[str] = []
    for key, label in labels.items():
        if key in value:
            lines.append(f"- {label}: `{value[key]}`")
    return lines or ["- Counts unavailable"]


def _visible_database_lines(value: Any) -> list[str]:
    if not isinstance(value, list) or not value:
        return ["- Visible non-system database list: none recorded"]
    max_display = 25
    shown = value[:max_display]
    line = "- Visible non-system database list: " + ", ".join(f"`{database}`" for database in shown)
    if len(value) > max_display:
        line += f", ... ({len(value) - max_display} more)"
    return [line]


def _scope_inventory_lines(value: Any) -> list[str]:
    if not isinstance(value, list) or not value:
        return ["- No scopes recorded"]
    lines: list[str] = []
    for idx, scope in enumerate(value, start=1):
        if not isinstance(scope, dict):
            continue
        title = _text(scope.get("name"), f"Scope {idx}")
        scope_id = _text(scope.get("scope_id"), f"scope-{idx}")
        lines.extend([
            f"### {scope_id} — {title}",
            f"- Status: {_text(scope.get('status'), 'unknown')}",
            f"- Databases: {_join_code(scope.get('databases'))}",
            f"- Objects in scope: {_join(scope.get('objects_in_scope'))}",
            f"- Controls used: {_join(scope.get('controls_used'))}",
            f"- Protected objects: {_join(scope.get('protected_objects'))}",
            f"- Unprotected sensitive candidates: {_join(scope.get('unprotected_sensitive_candidates'))}",
            f"- Key gaps: {_join(scope.get('key_gaps'))}",
        ])
        subscopes = scope.get("subscopes")
        if isinstance(subscopes, list) and subscopes:
            lines.append("- Subscopes:")
            for subscope in subscopes:
                lines.extend(_subscope_lines(subscope))
        lines.append("")
    while lines and lines[-1] == "":
        lines.pop()
    return lines


def _subscope_lines(value: Any) -> list[str]:
    if isinstance(value, str):
        return [f"  - {value}"]
    if not isinstance(value, dict):
        return []
    lines = [f"  - {_text(value.get('name'), 'unnamed subscope')}: {_text(value.get('status'), 'unknown')}"]
    for field, label in (
        ("objects", "objects"),
        ("protected_objects", "protected"),
        ("unprotected_sensitive_candidates", "unprotected candidates"),
        ("controls_used", "controls"),
    ):
        if value.get(field):
            lines.append(f"    - {label}: {_join(value.get(field))}")
    return lines


def _catalog_lines(catalog: dict[str, Any], live_governance: dict[str, Any]) -> list[str]:
    policies = catalog.get("policies") if isinstance(catalog.get("policies"), list) else live_governance.get("policies")
    tags = catalog.get("tags") if isinstance(catalog.get("tags"), list) else live_governance.get("tags")
    profiles = catalog.get("classification_profiles") if isinstance(catalog.get("classification_profiles"), list) else live_governance.get("classifications")
    classifiers = catalog.get("custom_classifiers") if isinstance(catalog.get("custom_classifiers"), list) else []
    return [
        "### Data Policies",
        *_object_lines(policies),
        "",
        "### Tags",
        *_object_lines(tags),
        "",
        "### Classification Profiles",
        *_object_lines(profiles),
        "",
        "### Custom Classifiers",
        *_object_lines(classifiers),
    ]


def _object_lines(value: Any) -> list[str]:
    if not isinstance(value, list) or not value:
        return ["- none observed"]
    lines: list[str] = []
    for item in value:
        if isinstance(item, dict):
            name = _text(item.get("name") or item.get("object_ref") or item.get("fqn"), "unknown")
            kind = _text(item.get("kind"), "object")
            behavior = item.get("behavior") or item.get("plain_english_behavior")
            used_by = item.get("used_by")
            line = f"- `{name}` ({kind})"
            if behavior:
                line += f" — {behavior}"
            if used_by:
                line += f" Used by: {_join(used_by)}."
            lines.append(line)
        else:
            lines.append(f"- {item}")
    return lines


def _join(value: Any) -> str:
    if not isinstance(value, list) or not value:
        return "none observed"
    return ", ".join(str(item) for item in value)


def _join_code(value: Any) -> str:
    if not isinstance(value, list) or not value:
        return "none observed"
    return ", ".join(f"`{item}`" for item in value)


def _text(value: Any, fallback: str) -> str:
    return value if isinstance(value, str) and value.strip() else fallback


def _optional_text(value: Any, fallback: str) -> str:
    if value is None:
        return fallback
    return str(value)
