"""Validation for Phase 2: Capture Intent."""

from __future__ import annotations

from typing import Any

from .common import artifact_state_path, has_user_agreement, phase_artifact, validate_artifact_location, validate_phase_log_entry


_REQUIRED_INTENT_HEADINGS = (
    "Purpose",
    "Artifact and State Locations",
    "Intent Capture Boundary",
    "Current Iteration Intent",
    "Account-Level Intent",
    "Scope-by-Scope Intent",
    "Explicit No-Protection / No-Change Decisions",
    "Future Candidates",
    "Deferred or Unknown Intent",
    "Unsupported Requests",
    "Traceability",
    "Planning Readiness",
)

_REQUIRED_SCOPE_INTENT_FIELDS = (
    "scope_path",
    "customer_intent",
    "data_or_objects",
    "desired_end_state",
    "open_questions",
)


def validate_artifact(state: dict[str, Any]) -> list[str]:
    errors = validate_phase_log_entry(state, 2, "capture_intent")
    artifact = phase_artifact(state, "capture_intent")
    if artifact is None:
        errors.append("missing phase_details.capture_intent")
    else:
        errors.extend(validate_artifact_location(artifact, "capture_intent", 2))
        errors.extend(_validate_capture_intent_artifact(artifact, state))
    raw_intent = state.get("raw_intent")
    if not isinstance(raw_intent, list) or not raw_intent:
        errors.append("raw_intent must contain at least one captured intent entry")
    return errors


def can_exit_phase(state: dict[str, Any]) -> bool:
    return not validate_artifact(state) and has_user_agreement(state, 2)


def render_consolidated_intent_summary(state: dict[str, Any]) -> str:
    artifact = phase_artifact(state, "capture_intent") or {}
    location = artifact.get("artifact_location", {}) if isinstance(artifact.get("artifact_location"), dict) else {}
    progress = artifact.get("progress", {}) if isinstance(artifact.get("progress"), dict) else {}
    scope_intents = artifact.get("scope_intents", [])
    account_level_intent = artifact.get("account_level_intent", [])

    lines = [
        "# Consolidated Intent Summary",
        "",
        "## Purpose",
        "This artifact records the customer's approved governance intent in natural language before implementation mechanisms are proposed in the Governance Spec.",
        "",
        "## Artifact and State Locations",
        "",
        f"- Generated at: `{_text(location.get('last_updated_at'), 'unknown')}`",
        f"- Working state: `{_text(artifact_state_path(location), 'unknown')}`",
        f"- Customer artifact: `{_text(location.get('customer_artifact_path'), 'unknown')}`",
        f"- Base committed version: `{_optional_text(progress.get('base_committed_version'), 'none')}`",
        "- Generated by: Intent-driven Governance skill, Phase 2 Capture Intent",
        "",
        "## Intent Capture Boundary",
        "This document captures desired outcomes and customer-named preferences. Final Snowflake mechanisms, reusable objects, policy bodies, classification profiles, and bindings are proposed in the Governance Spec phase.",
        "",
        "## Current Iteration Intent",
    ]
    lines.extend(_list_lines(artifact.get("current_iteration_intent", [])))

    lines.extend(["", "## Account-Level Intent"])
    lines.extend(_list_lines(account_level_intent))

    lines.extend(["", "## Scope-by-Scope Intent"])
    lines.extend(_scope_intent_lines(scope_intents))

    lines.extend(["", "## Explicit No-Protection / No-Change Decisions"])
    explicit = artifact.get("explicit_no_change_decisions")
    if isinstance(explicit, list):
        lines.extend(_list_lines(explicit))
    else:
        lines.extend(_explicit_no_change_lines(scope_intents))

    lines.extend(["", "## Future Candidates"])
    lines.extend(_future_candidate_lines(artifact.get("future_candidates", [])))

    lines.extend(["", "## Deferred or Unknown Intent"])
    open_questions = artifact.get("open_questions", [])
    lines.extend(_list_lines(open_questions))

    lines.extend(["", "## Unsupported Requests"])
    unsupported = artifact.get("unsupported_requests", [])
    lines.extend(_list_lines(unsupported))

    lines.extend(["", "## Traceability"])
    lines.extend(_traceability_lines(artifact))

    lines.extend(["", "## Planning Readiness"])
    if artifact.get("ready_for_derivation") is True and not open_questions:
        lines.append("- Ready to derive the Governance Spec.")
    elif artifact.get("ready_for_derivation") is True:
        lines.append("- Ready to derive the Governance Spec with documented open questions or deferrals.")
    else:
        lines.append("- Not ready to derive the Governance Spec; resolve open questions first.")
    return "\n".join(lines)


def _validate_capture_intent_artifact(artifact: dict[str, Any], state: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    summary = artifact.get("consolidated_intent_summary")
    if not isinstance(summary, str) or not summary.strip():
        errors.append("phase_details.capture_intent.consolidated_intent_summary must be a non-empty string")
    else:
        if "# Consolidated Intent Summary" not in summary:
            errors.append("phase_details.capture_intent.consolidated_intent_summary missing required title")
        for heading in _REQUIRED_INTENT_HEADINGS:
            if heading not in summary:
                errors.append(f"phase_details.capture_intent.consolidated_intent_summary missing required section: {heading}")

    if not isinstance(artifact.get("account_level_intent"), list) or not artifact.get("account_level_intent"):
        errors.append("phase_details.capture_intent.account_level_intent must be a non-empty list")

    if not isinstance(artifact.get("current_iteration_intent"), list) or not artifact.get("current_iteration_intent"):
        errors.append("phase_details.capture_intent.current_iteration_intent must be a non-empty list")
    if not isinstance(artifact.get("explicit_no_change_decisions"), list):
        errors.append("phase_details.capture_intent.explicit_no_change_decisions must be a list")
    if not isinstance(artifact.get("future_candidates"), list):
        errors.append("phase_details.capture_intent.future_candidates must be a list")

    scope_intents = artifact.get("scope_intents")
    if not isinstance(scope_intents, list) or not scope_intents:
        errors.append("phase_details.capture_intent.scope_intents must be a non-empty list")
    else:
        for idx, intent in enumerate(scope_intents):
            errors.extend(_validate_scope_intent(intent, idx))

    consolidated = artifact.get("consolidated_intents")
    if consolidated is not None and not isinstance(consolidated, list):
        errors.append("phase_details.capture_intent.consolidated_intents must be a list when present")

    raw_intent_ids = artifact.get("raw_intent_ids")
    if not isinstance(raw_intent_ids, list) or not raw_intent_ids:
        errors.append("phase_details.capture_intent.raw_intent_ids must be a non-empty list")
    else:
        valid_ids = {
            entry.get("id")
            for entry in state.get("raw_intent", [])
            if isinstance(entry, dict) and isinstance(entry.get("id"), str)
        }
        for raw_intent_id in raw_intent_ids:
            if raw_intent_id not in valid_ids:
                errors.append(
                    "phase_details.capture_intent.raw_intent_ids references "
                    f"unknown raw_intent id: {raw_intent_id}"
                )

    for list_field in ("open_questions", "unsupported_requests"):
        if list_field in artifact and not isinstance(artifact[list_field], list):
            errors.append(f"phase_details.capture_intent.{list_field} must be a list")

    open_questions = artifact.get("open_questions", [])
    if artifact.get("ready_for_derivation") is True and open_questions:
        errors.append("phase_details.capture_intent cannot be ready while open_questions is non-empty")
    if not isinstance(artifact.get("ready_for_derivation"), bool):
        errors.append("phase_details.capture_intent.ready_for_derivation must be a boolean")
    return errors


def _future_candidate_lines(value: Any) -> list[str]:
    if not isinstance(value, list) or not value:
        return ["- None captured"]
    lines: list[str] = []
    for item in value:
        if isinstance(item, dict):
            label = _text(item.get("summary") or item.get("id"), "future candidate")
            reason = item.get("reason")
            executable = item.get("executable_now")
            line = f"- {label}"
            if reason:
                line += f" — {reason}"
            if executable is False:
                line += " (not executable in the current iteration)"
            lines.append(line)
        else:
            lines.append(f"- {item}")
    return lines


def _validate_scope_intent(value: Any, idx: int) -> list[str]:
    errors: list[str] = []
    if not isinstance(value, dict):
        return [f"phase_details.capture_intent.scope_intents[{idx}] must be a mapping"]
    for field in _REQUIRED_SCOPE_INTENT_FIELDS:
        if field not in value:
            errors.append(f"phase_details.capture_intent.scope_intents[{idx}].{field} is required")
    for field in ("scope_path", "customer_intent", "desired_end_state"):
        if field in value and (not isinstance(value[field], str) or not value[field].strip()):
            errors.append(f"phase_details.capture_intent.scope_intents[{idx}].{field} must be a non-empty string")
    for list_field in (
        "data_or_objects",
        "open_questions",
        "customer_named_mechanisms",
        "explicit_no_protection_or_no_change",
        "source_observation_refs",
    ):
        if list_field in value and not isinstance(value[list_field], list):
            errors.append(f"phase_details.capture_intent.scope_intents[{idx}].{list_field} must be a list")
    if "why" in value and not isinstance(value["why"], str):
        errors.append(f"phase_details.capture_intent.scope_intents[{idx}].why must be a string when present")
    return errors


def _scope_intent_lines(value: Any) -> list[str]:
    if not isinstance(value, list) or not value:
        return ["- No scope intent captured"]
    lines: list[str] = []
    for idx, intent in enumerate(value, start=1):
        if not isinstance(intent, dict):
            continue
        lines.extend([
            f"### Scope {idx} — {_text(intent.get('scope_path'), 'unknown scope')}",
            f"- Customer intent: {_text(intent.get('customer_intent'), 'not captured')}",
            f"- Data or objects: {_join(intent.get('data_or_objects'))}",
            f"- Desired end state: {_text(intent.get('desired_end_state'), 'not captured')}",
            f"- Why: {_text(intent.get('why'), 'not provided')}",
            f"- Customer-named mechanisms: {_join(intent.get('customer_named_mechanisms'))}",
            f"- Source observation references: {_join(intent.get('source_observation_refs'))}",
        ])
        open_questions = intent.get("open_questions")
        if isinstance(open_questions, list) and open_questions:
            lines.append(f"- Open questions: {_join(open_questions)}")
        lines.append("")
    while lines and lines[-1] == "":
        lines.pop()
    return lines


def _explicit_no_change_lines(scope_intents: Any) -> list[str]:
    if not isinstance(scope_intents, list):
        return ["- None captured"]
    lines: list[str] = []
    for intent in scope_intents:
        if not isinstance(intent, dict):
            continue
        decisions = intent.get("explicit_no_protection_or_no_change")
        if isinstance(decisions, list):
            for decision in decisions:
                lines.append(f"- {_text(intent.get('scope_path'), 'unknown scope')}: {decision}")
    return lines or ["- None captured"]


def _traceability_lines(artifact: dict[str, Any]) -> list[str]:
    location = artifact.get("artifact_location", {}) if isinstance(artifact.get("artifact_location"), dict) else {}
    progress = artifact.get("progress", {}) if isinstance(artifact.get("progress"), dict) else {}
    return [
        f"- Working state path: {_text(artifact_state_path(location), 'unknown')}",
        f"- Customer artifact path: {_text(location.get('customer_artifact_path'), 'unknown')}",
        f"- Raw intent IDs: {_join(artifact.get('raw_intent_ids'))}",
        f"- Progress: {_text(progress.get('status'), 'unknown')}",
    ]


def _list_lines(value: Any) -> list[str]:
    if not isinstance(value, list) or not value:
        return ["- None"]
    return [f"- {item}" for item in value]


def _join(value: Any) -> str:
    if not isinstance(value, list) or not value:
        return "none captured"
    return ", ".join(str(item) for item in value)


def _text(value: Any, fallback: str) -> str:
    return value if isinstance(value, str) and value.strip() else fallback


def _optional_text(value: Any, fallback: str) -> str:
    if value is None:
        return fallback
    return str(value)
