"""Validation for Phase 3: Governance Spec."""

from __future__ import annotations

from typing import Any

from .common import artifact_state_path, has_delta, has_user_agreement, phase_artifact, validate_artifact_location, validate_phase_log_entry
from ..core import build_column_state, derive_intent, set_observed_masking_policy
from ..drift_monitor import validate_drift_contract
from ..operations import render_operations

_REQUIRED_SPEC_HEADINGS = (
    "Purpose",
    "Artifact and State Locations",
    "Spec Boundary",
    "Iteration Boundary",
    "Full Target Governance Baseline After This Version",
    "Target Account Overview",
    "Target Governance Scope Inventory",
    "Target Governance Object Catalog",
    "Implementation Delta",
    "Destructive Change Assessment",
    "Approved Intent Mapping",
    "Explicit No-Protection / No-Change Decisions",
    "Deferred / Unsupported / Remaining Gaps",
    "SQL Readiness",
)

_REQUIRED_TOP_LEVEL_FIELDS = (
    "approved_intent_mapping",
    "target_account_overview",
    "target_scope_inventory",
    "target_governance_object_catalog",
    "implementation_delta",
    "target_spec",
    "iteration_boundary",
)

_REQUIRED_TARGET_COUNTS = (
    "target_protected_objects",
    "newly_protected_objects",
    "policies_existing_reused",
    "policies_to_create",
    "tags_existing_reused",
    "tags_to_create",
    "tag_bindings_to_create",
    "classification_profiles_existing_reused",
    "classification_profiles_to_create",
    "custom_classifiers_existing_reused",
    "custom_classifiers_to_create",
)

_REQUIRED_SCOPE_FIELDS = (
    "scope_path",
    "target_status",
    "objects_in_scope",
    "existing_controls_preserved",
    "new_controls_to_apply",
    "resulting_protected_objects",
    "intentionally_unprotected_objects",
    "remaining_gaps_after_spec",
)

_CATALOG_FIELDS = ("policies", "tags", "classification_profiles", "custom_classifiers")
_DELTA_FIELDS = (
    "additive_changes",
    "preservations",
    "replacements",
    "removals",
    "weakening_changes",
    "broad_impact_changes",
    "destructive_changes",
    "no_op_no_change_decisions",
)
_REQUIRED_DESTRUCTIVE_FIELDS = ("id", "object", "type", "current_impact", "reason", "risk", "required_approval")


def validate_artifact(state: dict[str, Any]) -> list[str]:
    errors = validate_phase_log_entry(state, 3, "derive_specs_plan")
    artifact = phase_artifact(state, "derive_specs_plan")
    if artifact is None:
        errors.append("missing phase_details.derive_specs_plan")
    else:
        errors.extend(validate_artifact_location(artifact, "derive_specs_plan", 3))
        errors.extend(_validate_governance_spec_artifact(artifact, state))
    if not isinstance(state.get("intent_artifacts"), dict):
        errors.append("intent_artifacts must be present")
    if not has_delta(state):
        errors.append("delta must be present")
    if not state.get("scoped_digest"):
        errors.append("scoped_digest is required")
    return errors


def can_exit_phase(state: dict[str, Any]) -> bool:
    return not validate_artifact(state) and has_user_agreement(state, 3)


def render_spec_plan_summary(state: dict[str, Any]) -> str:
    artifact = phase_artifact(state, "derive_specs_plan") or {}
    location = artifact.get("artifact_location", {}) if isinstance(artifact.get("artifact_location"), dict) else {}
    progress = artifact.get("progress", {}) if isinstance(artifact.get("progress"), dict) else {}
    boundary = artifact.get("spec_boundary", {}) if isinstance(artifact.get("spec_boundary"), dict) else {}
    lines = [
        "# Governance Spec — Target Governance Status",
        "",
        "## Purpose",
        "This artifact defines the target governance status to implement after approval.",
        "",
        "## Artifact and State Locations",
        f"- Generated at: `{_text(location.get('last_updated_at'), 'unknown')}`",
        f"- Working state: `{_text(artifact_state_path(location), 'unknown')}`",
        f"- Customer artifact: `{_text(location.get('customer_artifact_path'), 'unknown')}`",
        f"- Base committed version: `{_optional_text(progress.get('base_committed_version'), 'none')}`",
        f"- Source observation: `{_text(artifact.get('source_observation_artifact'), 'unknown')}`",
        f"- Source intent: `{_text(artifact.get('source_intent_artifact'), 'unknown')}`",
        "- Generated by: Intent-driven Governance skill, Phase 3 Governance Spec",
        "",
        "## Spec Boundary",
        f"- Covers: {_text(boundary.get('covers'), 'approved intent scope')}",
        f"- Excludes: {_join(boundary.get('excludes'))}",
        f"- Additive only: {boundary.get('additive_only') is True}",
        f"- Future/discovery behavior included: {boundary.get('future_or_discovery_behavior_included') is True}",
        "",
        "## Iteration Boundary",
    ]
    lines.extend(_iteration_boundary_lines(artifact.get("iteration_boundary")))

    lines.extend(["", "## Full Target Governance Baseline After This Version"])
    lines.extend(_target_spec_lines(artifact.get("target_spec")))

    lines.extend(["", "## Target Account Overview"])
    lines.extend(_count_lines(artifact.get("target_account_overview")))

    lines.extend(["", "## Target Governance Scope Inventory"])
    lines.extend(_target_scope_lines(artifact.get("target_scope_inventory")))

    lines.extend(["", "## Target Governance Object Catalog"])
    lines.extend(_target_catalog_lines(artifact.get("target_governance_object_catalog")))

    lines.extend(["", "## Implementation Delta"])
    lines.extend(_implementation_delta_lines(artifact.get("implementation_delta")))

    lines.extend(["", "## Destructive Change Assessment"])
    lines.extend(_destructive_assessment_lines(artifact))

    lines.extend(["", "## Approved Intent Mapping"])
    lines.extend(_approved_intent_lines(artifact.get("approved_intent_mapping")))

    lines.extend(["", "## Scheduled Drift Monitoring"])
    lines.extend(_scheduled_monitoring_lines(artifact.get("monitoring_intent")))

    lines.extend(["", "## Explicit No-Protection / No-Change Decisions"])
    lines.extend(_list_lines(_collect_no_change_decisions(artifact)))

    lines.extend(["", "## Deferred / Unsupported / Remaining Gaps"])
    combined_gaps = []
    for field in ("unresolved_items", "unsupported_requests", "remaining_gaps"):
        value = artifact.get(field)
        if isinstance(value, list):
            combined_gaps.extend(value)
    lines.extend(_list_lines(combined_gaps))

    lines.extend(["", "## SQL Readiness"])
    if artifact.get("ready_for_sql_generation") is True:
        lines.append("- Ready to generate exact SQL for review.")
    else:
        lines.append("- Not ready to generate SQL until blockers are resolved.")
    blockers = artifact.get("sql_readiness_blockers", [])
    if isinstance(blockers, list) and blockers:
        lines.append(f"- Blockers: {_join(blockers)}")
    return "\n".join(lines)


def plan_one_table_masking(
    *,
    scope: str,
    table_fqn: str,
    mask_columns: list[str],
    unprotected_columns: list[str],
    observed_policy_columns: list[str] | None = None,
    except_role: str = "ACCOUNTADMIN",
    raw_statement: str | None = None,
    who: str = "user",
    when: str = "unknown",
    context: str = "intent capture",
) -> dict[str, Any]:
    state = build_column_state(
        scope=scope,
        table_fqn=table_fqn,
        mask_columns=mask_columns,
        unprotected_columns=unprotected_columns,
        except_role=except_role,
        raw_statement=raw_statement,
        who=who,
        when=when,
        context=context,
    )
    for item in observed_policy_columns or []:
        column, _, role = item.partition("=")
        set_observed_masking_policy(
            state,
            table_fqn,
            column,
            except_role=role or except_role,
        )
    return derive_intent(state)


def _validate_governance_spec_artifact(artifact: dict[str, Any], state: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    for field in _REQUIRED_TOP_LEVEL_FIELDS:
        if field not in artifact:
            errors.append(f"phase_details.derive_specs_plan.{field} is required")

    summary = artifact.get("governance_spec_summary")
    if not isinstance(summary, str) or not summary.strip():
        errors.append("phase_details.derive_specs_plan.governance_spec_summary must be a non-empty string")
    else:
        if "# Governance Spec — Target Governance Status" not in summary:
            errors.append("phase_details.derive_specs_plan.governance_spec_summary missing required title")
        for heading in _REQUIRED_SPEC_HEADINGS:
            if heading not in summary:
                errors.append(f"phase_details.derive_specs_plan.governance_spec_summary missing required section: {heading}")

    errors.extend(_validate_approved_intent_mapping(artifact.get("approved_intent_mapping"), state))
    errors.extend(_validate_target_account_overview(artifact.get("target_account_overview")))
    errors.extend(_validate_target_scope_inventory(artifact.get("target_scope_inventory"), state))
    errors.extend(_validate_target_catalog(artifact.get("target_governance_object_catalog")))
    errors.extend(_validate_implementation_delta(artifact))
    errors.extend(_validate_iteration_boundary(artifact.get("iteration_boundary"), state))
    errors.extend(_validate_implementation_operations(artifact.get("implementation_operations")))
    errors.extend(_validate_monitoring_intent(artifact))

    errors.extend(_validate_target_spec_baseline(artifact.get("target_spec"), artifact.get("target_scope_inventory")))
    for field in ("unresolved_items", "unsupported_requests", "remaining_gaps", "sql_readiness_blockers"):
        if field in artifact and not isinstance(artifact[field], list):
            errors.append(f"phase_details.derive_specs_plan.{field} must be a list")

    ready = artifact.get("ready_for_sql_generation")
    if not isinstance(ready, bool):
        errors.append("phase_details.derive_specs_plan.ready_for_sql_generation must be a boolean")
    elif ready:
        if artifact.get("unresolved_items"):
            errors.append("phase_details.derive_specs_plan cannot be ready while unresolved_items is non-empty")
        if artifact.get("sql_readiness_blockers"):
            errors.append("phase_details.derive_specs_plan cannot be ready while sql_readiness_blockers is non-empty")
        if not isinstance(state.get("intent_artifacts"), dict):
            errors.append("intent_artifacts must be present before SQL generation")
        if not has_delta(state):
            errors.append("delta must be present before SQL generation")
        if not state.get("scoped_digest"):
            errors.append("scoped_digest must be present before SQL generation")
        errors.extend(_validate_destructive_approval_for_readiness(artifact))
    return errors


def _validate_monitoring_intent(artifact: dict[str, Any]) -> list[str]:
    value = artifact.get("monitoring_intent")
    if value in (None, {}, []):
        summary = artifact.get("governance_spec_summary", "")
        if isinstance(summary, str) and "## Scheduled Drift Monitoring" in summary:
            return []
        return []
    if not isinstance(value, dict):
        return ["phase_details.derive_specs_plan.monitoring_intent must be a mapping when present"]
    errors: list[str] = []
    enabled = value.get("enabled")
    if not isinstance(enabled, bool):
        errors.append("phase_details.derive_specs_plan.monitoring_intent.enabled must be a boolean")
    if enabled:
        for field in ("schedule", "baseline_tracking", "monitor_execution_role", "notification", "no_auto_remediation"):
            if field not in value:
                errors.append(f"phase_details.derive_specs_plan.monitoring_intent.{field} is required when enabled")
        if value.get("no_auto_remediation") is not True:
            errors.append("phase_details.derive_specs_plan.monitoring_intent.no_auto_remediation must be true")
        if not isinstance(value.get("monitored_assertion_types"), list) or not value.get("monitored_assertion_types"):
            errors.append("phase_details.derive_specs_plan.monitoring_intent.monitored_assertion_types must be a non-empty list")
        notification = value.get("notification")
        if not isinstance(notification, dict):
            errors.append("phase_details.derive_specs_plan.monitoring_intent.notification must be a mapping")
        elif not isinstance(notification.get("integration_name"), str) or not notification.get("integration_name", "").strip():
            errors.append("phase_details.derive_specs_plan.monitoring_intent.notification.integration_name must reference an existing integration")
        elif not _non_empty_text_list(notification.get("recipients")):
            errors.append("phase_details.derive_specs_plan.monitoring_intent.notification.recipients must be a non-empty list")
        drift_contract = value.get("drift_contract")
        if not isinstance(drift_contract, dict):
            errors.append("phase_details.derive_specs_plan.monitoring_intent.drift_contract must be a mapping when enabled")
        else:
            errors.extend(f"phase_details.derive_specs_plan.monitoring_intent.{error}" for error in validate_drift_contract(drift_contract))
        monitorability = value.get("monitorability")
        if monitorability not in {"fully_monitorable", "partially_monitorable", "manual_review_required"}:
            errors.append("phase_details.derive_specs_plan.monitoring_intent.monitorability must declare coverage")
        summary = artifact.get("governance_spec_summary", "")
        if isinstance(summary, str) and "## Scheduled Drift Monitoring" not in summary:
            errors.append("phase_details.derive_specs_plan.governance_spec_summary missing Scheduled Drift Monitoring section")
    return errors


def _validate_iteration_boundary(value: Any, state: dict[str, Any]) -> list[str]:
    if not isinstance(value, dict):
        return ["phase_details.derive_specs_plan.iteration_boundary must be a mapping"]
    errors: list[str] = []
    for field in ("goal", "maturity_moves", "allowed_changes", "forbidden_changes", "future_candidates"):
        if field not in value:
            errors.append(f"phase_details.derive_specs_plan.iteration_boundary.{field} is required")
    if "goal" in value and (not isinstance(value["goal"], str) or not value["goal"].strip()):
        errors.append("phase_details.derive_specs_plan.iteration_boundary.goal must be a non-empty string")
    for list_field in ("maturity_moves", "allowed_changes", "forbidden_changes", "future_candidates"):
        if list_field in value and not isinstance(value[list_field], list):
            errors.append(f"phase_details.derive_specs_plan.iteration_boundary.{list_field} must be a list")
    if isinstance(value.get("future_candidates"), list):
        errors.extend(_validate_future_candidate_carry_forward(value["future_candidates"], state))
    return errors


def _non_empty_text_list(value: Any) -> bool:
    return isinstance(value, list) and bool(value) and all(isinstance(item, str) and item.strip() for item in value)


def _validate_future_candidate_carry_forward(spec_candidates: list[Any], state: dict[str, Any]) -> list[str]:
    capture = phase_artifact(state, "capture_intent") or {}
    intent_candidates = capture.get("future_candidates", [])
    if not isinstance(intent_candidates, list):
        return []

    required_ids: set[str] = set()
    required_legacy_text: set[str] = set()
    for candidate in intent_candidates:
        if isinstance(candidate, dict):
            candidate_id = candidate.get("id")
            executable_now = candidate.get("executable_now")
            if isinstance(candidate_id, str) and candidate_id.strip() and executable_now is not True:
                required_ids.add(candidate_id.strip())
        elif isinstance(candidate, str) and candidate.strip():
            required_legacy_text.add(candidate.strip())

    carried_ids: set[str] = set()
    carried_legacy_text: set[str] = set()
    for candidate in spec_candidates:
        if isinstance(candidate, dict):
            candidate_id = candidate.get("id")
            if isinstance(candidate_id, str) and candidate_id.strip():
                carried_ids.add(candidate_id.strip())
        elif isinstance(candidate, str) and candidate.strip():
            candidate_text = candidate.strip()
            carried_ids.add(candidate_text)
            carried_legacy_text.add(candidate_text)

    missing = sorted((required_ids - carried_ids) | (required_legacy_text - carried_legacy_text))
    if missing:
        return [
            "phase_details.derive_specs_plan.iteration_boundary.future_candidates "
            f"must carry forward Phase 2 future candidate(s): {', '.join(missing)}"
        ]
    return []


def _iteration_boundary_lines(value: Any) -> list[str]:
    if not isinstance(value, dict):
        return ["- Iteration boundary not recorded"]
    return [
        f"- Goal: {_text(value.get('goal'), 'not recorded')}",
        f"- Maturity moves: {_join(value.get('maturity_moves'))}",
        f"- Allowed changes this iteration: {_join(value.get('allowed_changes'))}",
        f"- Forbidden changes this iteration: {_join(value.get('forbidden_changes'))}",
        f"- Future candidates: {_join(value.get('future_candidates'))}",
    ]


def _target_spec_lines(value: Any) -> list[str]:
    if isinstance(value, str) and value.strip():
        return [line if line.strip() else "" for line in value.strip().splitlines()]
    if not isinstance(value, dict) or not value:
        return ["- Full target-state baseline not recorded"]

    lines: list[str] = []
    for key, item in value.items():
        raw_label = str(key).strip()
        label = raw_label if "." in raw_label or raw_label.isupper() else raw_label.replace("_", " ").title()
        if isinstance(item, dict):
            lines.append(f"### {label}")
            for child_key, child_value in item.items():
                child_label = str(child_key).replace("_", " ")
                if isinstance(child_value, list):
                    lines.append(f"- {child_label}: {_join(child_value)}")
                else:
                    lines.append(f"- {child_label}: {_text(child_value, 'not recorded')}")
        elif isinstance(item, list):
            lines.append(f"### {label}")
            lines.extend(_list_lines(item))
        else:
            lines.append(f"- {label}: {_text(item, 'not recorded')}")
    return lines


def _validate_target_spec_baseline(value: Any, scope_inventory: Any) -> list[str]:
    if not isinstance(value, (dict, str)) or not value:
        return ["phase_details.derive_specs_plan.target_spec must be a non-empty mapping or string"]
    scopes = []
    if isinstance(scope_inventory, list):
        scopes = [
            item.get("scope_path")
            for item in scope_inventory
            if isinstance(item, dict) and isinstance(item.get("scope_path"), str) and item.get("scope_path", "").strip()
        ]
    if not scopes:
        return ["phase_details.derive_specs_plan.target_spec cannot be validated without target_scope_inventory scope_path entries"]
    text = value if isinstance(value, str) else _target_spec_search_text(value)
    missing = [scope for scope in scopes if scope not in text]
    if missing:
        return [
            "phase_details.derive_specs_plan.target_spec must restate the full target baseline for each target scope; "
            f"missing scope(s): {', '.join(missing)}"
        ]
    return []


def _target_spec_search_text(value: Any) -> str:
    if isinstance(value, dict):
        parts: list[str] = []
        for key, child in value.items():
            parts.append(str(key))
            parts.append(_target_spec_search_text(child))
        return "\n".join(parts)
    if isinstance(value, list):
        return "\n".join(_target_spec_search_text(item) for item in value)
    return str(value)


def _validate_implementation_operations(value: Any) -> list[str]:
    if value is None:
        return []
    if not isinstance(value, list) or not value:
        return ["phase_details.derive_specs_plan.implementation_operations must be a non-empty list when present"]
    try:
        render_operations(value)
    except Exception as exc:
        return [f"phase_details.derive_specs_plan.implementation_operations invalid: {exc}"]
    return []


def _validate_approved_intent_mapping(value: Any, state: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    if not isinstance(value, list) or not value:
        return ["phase_details.derive_specs_plan.approved_intent_mapping must be a non-empty list"]
    planned_refs = set()
    for idx, item in enumerate(value):
        if not isinstance(item, dict):
            errors.append(f"phase_details.derive_specs_plan.approved_intent_mapping[{idx}] must be a mapping")
            continue
        for field in ("scope_path", "customer_intent", "target_status", "spec_items"):
            if field not in item:
                errors.append(f"phase_details.derive_specs_plan.approved_intent_mapping[{idx}].{field} is required")
        if isinstance(item.get("scope_path"), str):
            planned_refs.add(item["scope_path"])
        if "spec_items" in item and not isinstance(item["spec_items"], list):
            errors.append(f"phase_details.derive_specs_plan.approved_intent_mapping[{idx}].spec_items must be a list")
    capture = phase_artifact(state, "capture_intent") or {}
    for scope_intent in capture.get("scope_intents", []):
        if not isinstance(scope_intent, dict):
            continue
        scope_path = scope_intent.get("scope_path")
        if isinstance(scope_path, str) and scope_path not in planned_refs:
            errors.append(f"approved scope intent {scope_path!r} is not mapped in approved_intent_mapping")
    return errors


def _validate_target_account_overview(value: Any) -> list[str]:
    if not isinstance(value, dict):
        return ["phase_details.derive_specs_plan.target_account_overview must be a mapping"]
    counts = value.get("counts")
    if not isinstance(counts, dict):
        return ["phase_details.derive_specs_plan.target_account_overview.counts must be a mapping"]
    errors = []
    for field in _REQUIRED_TARGET_COUNTS:
        if field not in counts:
            errors.append(f"phase_details.derive_specs_plan.target_account_overview.counts.{field} is required")
    return errors


def _validate_target_scope_inventory(value: Any, state: dict[str, Any]) -> list[str]:
    if not isinstance(value, list) or not value:
        return ["phase_details.derive_specs_plan.target_scope_inventory must be a non-empty list"]
    errors: list[str] = []
    target_paths = set()
    for idx, item in enumerate(value):
        if not isinstance(item, dict):
            errors.append(f"phase_details.derive_specs_plan.target_scope_inventory[{idx}] must be a mapping")
            continue
        for field in _REQUIRED_SCOPE_FIELDS:
            if field not in item:
                errors.append(f"phase_details.derive_specs_plan.target_scope_inventory[{idx}].{field} is required")
        if isinstance(item.get("scope_path"), str):
            target_paths.add(item["scope_path"])
        for list_field in (
            "objects_in_scope",
            "existing_controls_preserved",
            "new_controls_to_apply",
            "resulting_protected_objects",
            "intentionally_unprotected_objects",
            "remaining_gaps_after_spec",
            "subscopes",
        ):
            if list_field in item and not isinstance(item[list_field], list):
                errors.append(f"phase_details.derive_specs_plan.target_scope_inventory[{idx}].{list_field} must be a list")
    observe = phase_artifact(state, "observe") or {}
    observed_scopes = observe.get("scope_inventory", [])
    for observed in observed_scopes:
        if not isinstance(observed, dict):
            continue
        observed_path = observed.get("name") or observed.get("scope_path") or observed.get("scope_id")
        if isinstance(observed_path, str) and observed_path not in target_paths:
            errors.append(f"observed scope {observed_path!r} is not represented in target_scope_inventory")
    return errors


def _validate_target_catalog(value: Any) -> list[str]:
    if not isinstance(value, dict):
        return ["phase_details.derive_specs_plan.target_governance_object_catalog must be a mapping"]
    errors: list[str] = []
    for field in _CATALOG_FIELDS:
        items = value.get(field)
        if not isinstance(items, list):
            errors.append(f"phase_details.derive_specs_plan.target_governance_object_catalog.{field} must be a list")
            continue
        for idx, item in enumerate(items):
            if not isinstance(item, dict):
                errors.append(f"phase_details.derive_specs_plan.target_governance_object_catalog.{field}[{idx}] must be a mapping")
                continue
            for required in ("name", "kind", "status"):
                if not isinstance(item.get(required), str) or not item.get(required, "").strip():
                    errors.append(f"phase_details.derive_specs_plan.target_governance_object_catalog.{field}[{idx}].{required} is required")
            if field == "policies" and not isinstance(item.get("behavior"), str):
                errors.append(f"phase_details.derive_specs_plan.target_governance_object_catalog.policies[{idx}].behavior is required")
    return errors


def _validate_implementation_delta(artifact: dict[str, Any]) -> list[str]:
    value = artifact.get("implementation_delta")
    if not isinstance(value, dict):
        return ["phase_details.derive_specs_plan.implementation_delta must be a mapping"]
    errors: list[str] = []
    for field in _DELTA_FIELDS:
        if not isinstance(value.get(field), list):
            errors.append(f"phase_details.derive_specs_plan.implementation_delta.{field} must be a list")
    destructive = value.get("destructive_changes", []) if isinstance(value.get("destructive_changes"), list) else []
    destructive_ids = set()
    for idx, item in enumerate(destructive):
        if not isinstance(item, dict):
            errors.append(f"phase_details.derive_specs_plan.implementation_delta.destructive_changes[{idx}] must be a mapping")
            continue
        for field in _REQUIRED_DESTRUCTIVE_FIELDS:
            if not isinstance(item.get(field), str) or not item.get(field, "").strip():
                errors.append(f"phase_details.derive_specs_plan.implementation_delta.destructive_changes[{idx}].{field} is required")
        if isinstance(item.get("id"), str):
            destructive_ids.add(item["id"])
    approval = artifact.get("destructive_change_approval")
    if destructive and approval is not None:
        errors.extend(_validate_destructive_approval(approval, destructive_ids))
    return errors


def _validate_destructive_approval_for_readiness(artifact: dict[str, Any]) -> list[str]:
    delta = artifact.get("implementation_delta", {}) if isinstance(artifact.get("implementation_delta"), dict) else {}
    destructive = delta.get("destructive_changes", []) if isinstance(delta.get("destructive_changes"), list) else []
    if not destructive:
        return []
    destructive_ids = {item.get("id") for item in destructive if isinstance(item, dict) and isinstance(item.get("id"), str)}
    approval = artifact.get("destructive_change_approval")
    if approval is None:
        return ["phase_details.derive_specs_plan.destructive_change_approval is required before SQL generation"]
    return _validate_destructive_approval(approval, destructive_ids)


def _validate_destructive_approval(value: Any, destructive_ids: set[str]) -> list[str]:
    if not isinstance(value, dict):
        return ["phase_details.derive_specs_plan.destructive_change_approval must be a mapping"]
    errors: list[str] = []
    for field in ("approved_by", "approved_at", "approval_text"):
        if not isinstance(value.get(field), str) or not value.get(field, "").strip():
            errors.append(f"phase_details.derive_specs_plan.destructive_change_approval.{field} is required")
    approved_items = value.get("approved_items")
    if not isinstance(approved_items, list):
        errors.append("phase_details.derive_specs_plan.destructive_change_approval.approved_items must be a list")
    else:
        missing = sorted(destructive_ids - {str(item) for item in approved_items})
        if missing:
            errors.append(f"destructive_change_approval does not cover destructive item(s): {missing}")
    return errors


def _count_lines(value: Any) -> list[str]:
    if not isinstance(value, dict):
        return ["- Counts unavailable"]
    counts = value.get("counts") if isinstance(value.get("counts"), dict) else {}
    if not counts:
        return ["- Counts unavailable"]
    labels = {
        "target_protected_objects": "Target protected objects",
        "newly_protected_objects": "Newly protected objects",
        "policies_existing_reused": "Policies existing/reused",
        "policies_to_create": "Policies to create",
        "tags_existing_reused": "Tags existing/reused",
        "tags_to_create": "Tags to create",
        "tag_bindings_to_create": "Tag bindings to create",
        "classification_profiles_existing_reused": "Classification profiles existing/reused",
        "classification_profiles_to_create": "Classification profiles to create",
        "custom_classifiers_existing_reused": "Custom classifiers existing/reused",
        "custom_classifiers_to_create": "Custom classifiers to create",
    }
    return [f"- {label}: `{counts[key]}`" for key, label in labels.items() if key in counts]


def _target_scope_lines(value: Any) -> list[str]:
    if not isinstance(value, list) or not value:
        return ["- No target scopes recorded"]
    lines: list[str] = []
    for item in value:
        if not isinstance(item, dict):
            continue
        lines.extend([
            f"### {_text(item.get('scope_path'), 'unknown scope')}",
            f"- Target status: {_text(item.get('target_status'), 'unknown')}",
            f"- Objects in scope: {_join(item.get('objects_in_scope'))}",
            f"- Existing controls preserved: {_join(item.get('existing_controls_preserved'))}",
            f"- New controls to apply: {_join(item.get('new_controls_to_apply'))}",
            f"- Resulting protected objects: {_join(item.get('resulting_protected_objects'))}",
            f"- Intentionally unprotected objects: {_join(item.get('intentionally_unprotected_objects'))}",
            f"- Remaining gaps after spec: {_join(item.get('remaining_gaps_after_spec'))}",
        ])
        subscopes = item.get("subscopes")
        if isinstance(subscopes, list) and subscopes:
            lines.append("- Subscopes:")
            for subscope in subscopes:
                lines.extend(_subscope_lines(subscope))
        lines.append("")
    while lines and lines[-1] == "":
        lines.pop()
    return lines


def _subscope_lines(value: Any) -> list[str]:
    if isinstance(value, str):
        return [f"  - {value}"]
    if not isinstance(value, dict):
        return []
    lines = [f"  - {_text(value.get('name'), 'unnamed subscope')}: {_text(value.get('target_status'), 'unknown')}"]
    for field, label in (
        ("resulting_protected_objects", "protected"),
        ("new_controls_to_apply", "new controls"),
        ("intentionally_unprotected_objects", "intentionally unprotected"),
    ):
        if value.get(field):
            lines.append(f"    - {label}: {_join(value.get(field))}")
    return lines


def _target_catalog_lines(value: Any) -> list[str]:
    if not isinstance(value, dict):
        return ["- No target governance objects recorded"]
    lines: list[str] = []
    headings = {
        "policies": "Data Policies",
        "tags": "Tags",
        "classification_profiles": "Classification Profiles",
        "custom_classifiers": "Custom Classifiers",
    }
    for field, heading in headings.items():
        lines.extend([f"### {heading}"])
        lines.extend(_catalog_object_lines(value.get(field)))
        lines.append("")
    while lines and lines[-1] == "":
        lines.pop()
    return lines


def _catalog_object_lines(value: Any) -> list[str]:
    if not isinstance(value, list) or not value:
        return ["- none"]
    lines: list[str] = []
    for item in value:
        if not isinstance(item, dict):
            lines.append(f"- {item}")
            continue
        line = f"- `{_text(item.get('name'), 'unknown')}` ({_text(item.get('kind'), 'object')}; {_text(item.get('status'), 'unknown status')})"
        behavior = item.get("behavior")
        if behavior:
            line += f" — {behavior}"
        applies_to = item.get("applies_to")
        if applies_to:
            line += f" Applies to: {_join(applies_to)}."
        lines.append(line)
    return lines


def _implementation_delta_lines(value: Any) -> list[str]:
    if not isinstance(value, dict):
        return ["- No implementation delta recorded"]
    labels = {
        "additive_changes": "Additive changes",
        "preservations": "Preservations",
        "replacements": "Replacements",
        "removals": "Removals",
        "weakening_changes": "Weakening changes",
        "broad_impact_changes": "Broad-impact changes",
        "destructive_changes": "Destructive changes",
        "no_op_no_change_decisions": "No-op/no-change decisions",
    }
    lines: list[str] = []
    for field, label in labels.items():
        lines.append(f"### {label}")
        lines.extend(_list_lines(value.get(field)))
        lines.append("")
    while lines and lines[-1] == "":
        lines.pop()
    return lines


def _destructive_assessment_lines(artifact: dict[str, Any]) -> list[str]:
    delta = artifact.get("implementation_delta", {}) if isinstance(artifact.get("implementation_delta"), dict) else {}
    destructive = delta.get("destructive_changes", []) if isinstance(delta.get("destructive_changes"), list) else []
    lines = [f"- Destructive changes proposed: {'yes' if destructive else 'no'}"]
    if not destructive:
        lines.extend([
            "- Replacements: none",
            "- Removals: none",
            "- Weakening changes: none",
            "- Broad-impact changes: none",
        ])
        return lines
    for item in destructive:
        if not isinstance(item, dict):
            continue
        lines.extend([
            f"### {_text(item.get('id'), 'destructive-change')} — {_text(item.get('object'), 'unknown object')}",
            f"- Type: {_text(item.get('type'), 'unknown')}",
            f"- Current impact: {_text(item.get('current_impact'), 'unknown')}",
            f"- Reason: {_text(item.get('reason'), 'unknown')}",
            f"- Risk: {_text(item.get('risk'), 'unknown')}",
            f"- Required approval: {_text(item.get('required_approval'), 'explicit destructive-change approval')}",
        ])
    approval = artifact.get("destructive_change_approval")
    if isinstance(approval, dict):
        lines.append(f"- Approval recorded: {_text(approval.get('approval_text'), 'yes')}")
    else:
        lines.append("- Approval recorded: no")
    return lines


def _approved_intent_lines(value: Any) -> list[str]:
    if not isinstance(value, list) or not value:
        return ["- No approved intent mapping recorded"]
    lines: list[str] = []
    for item in value:
        if not isinstance(item, dict):
            continue
        lines.extend([
            f"### {_text(item.get('scope_path'), 'unknown scope')}",
            f"- Customer intent: {_text(item.get('customer_intent'), 'not captured')}",
            f"- Target status: {_text(item.get('target_status'), 'unknown')}",
            f"- Spec items: {_join(item.get('spec_items'))}",
        ])
    return lines


def _scheduled_monitoring_lines(value: Any) -> list[str]:
    if not isinstance(value, dict) or value.get("enabled") is not True:
        return ["- Scheduled drift monitoring was not requested for this iteration."]
    notification = value.get("notification", {}) if isinstance(value.get("notification"), dict) else {}
    return [
        "- Scheduled drift monitoring is part of the approved governance intent.",
        f"- Schedule: {_text(value.get('schedule'), 'not specified')}",
        f"- Baseline tracking: {_text(value.get('baseline_tracking'), 'not specified')}",
        f"- Monitor execution role: {_text(value.get('monitor_execution_role'), 'not specified')}",
        f"- Monitorability: {_text(value.get('monitorability'), 'not declared')}",
        f"- Assertion types: {_join(value.get('monitored_assertion_types'))}",
        f"- Notification integration: {_text(notification.get('integration_name'), 'not specified')}",
        "- Automatic remediation: disabled; findings must return to CoCo review and explicit approval.",
    ]


def _collect_no_change_decisions(artifact: dict[str, Any]) -> list[Any]:
    decisions: list[Any] = []
    delta = artifact.get("implementation_delta", {}) if isinstance(artifact.get("implementation_delta"), dict) else {}
    if isinstance(delta.get("no_op_no_change_decisions"), list):
        decisions.extend(delta["no_op_no_change_decisions"])
    for scope in artifact.get("target_scope_inventory", []):
        if isinstance(scope, dict) and isinstance(scope.get("intentionally_unprotected_objects"), list):
            for item in scope["intentionally_unprotected_objects"]:
                decisions.append(f"{_text(scope.get('scope_path'), 'unknown scope')}: {item}")
    return decisions


def _list_lines(value: Any) -> list[str]:
    if not isinstance(value, list) or not value:
        return ["- None"]
    lines = []
    for item in value:
        if isinstance(item, dict):
            label = item.get("id") or item.get("object") or item.get("description") or item
            lines.append(f"- {label}")
        else:
            lines.append(f"- {item}")
    return lines


def _join(value: Any) -> str:
    if not isinstance(value, list) or not value:
        return "none"
    return ", ".join(str(item) for item in value)


def _text(value: Any, fallback: str) -> str:
    return value if isinstance(value, str) and value.strip() else fallback


def _optional_text(value: Any, fallback: str) -> str:
    if value is None:
        return fallback
    return str(value)
